name: p3pch4t
description: p3p chat

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+100000

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: 1.4.1
  shelf_router: 1.1.4
  openpgp: 3.4.0
  shared_preferences: 2.2.3
  objectbox: 2.5.0
  path_provider: 2.1.3
  path: ^1.8.2
  http: 1.2.2
  random_string: 2.3.1
  objectbox_flutter_libs: any
  flutter_background_service: 5.0.6
  flutter_local_notifications: 17.2.1+2
  file_picker: 8.0.5
  async: 2.11.0
  crypto: 3.0.3
  convert: 3.1.1
  filesize: 2.0.1
  permission_handler: 11.3.1
  i2p_flutter:
    path: ../i2p_flutter
  dio: 5.5.0+1
  mime: 1.0.5
  markdown: 7.2.2
  flutter_markdown: 0.7.3
  pretty_qr_code: 3.3.0
  qr: 3.0.1
  open_filex: 4.4.0
  flutter_zxing: 1.7.0
  mobile_scanner: 5.1.1
  flex_color_picker: 3.4.1
  flutter_svg: 2.0.10+1
  select_dialog: 2.0.2
  cross_file: 0.3.4+1
  share_plus: 9.0.0
  duration: 3.0.13
  url_launcher: 6.3.0
  table_calendar: 3.1.2
  date_format: 2.0.7
  flutter_expandable_fab: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  objectbox_generator: any

dependency_overrides:
  watcher: 1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/images/help/
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
