name: p3pch4t
description: Peer to peer chat
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  p3p:
    path: ../p3p.dart
  ssmdc:
    path: ../ssmdc.dart
  path_provider: ^2.1.0
  dart_pg: ^1.1.5
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  open_file: ^3.3.2
  permission_handler: ^10.4.3
  webview_flutter: ^4.2.2
  path: ^1.8.3
  archive: ^3.3.7
  shelf: ^1.4.1
  mime: ^1.0.4
  url_launcher: ^6.1.12
  http: ^1.1.0
  flutter_local_notifications: ^15.1.0+1
  flutter_background_service: ^5.0.1
  sqlite3_flutter_libs: ^0.5.0
  flutter_background_service_android: ^6.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true 
  assets:
    - assets/git-changes.md