name: Android Release
run-name: Building P3pch4t for android
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  compat-check:
    runs-on: androidsdk-flutter
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Flutter pub get
        run: |
          cd ${{ gitea.workspace }} \
          && flutter pub get
      - name: make version
        run: |
          cd ${{ gitea.workspace }} \
          && make version
      - name: flutter analyze
        run: |
          cd ${{ gitea.workspace }} \
          && flutter analyze
      - name: Build apk
        continue-on-error: false
        run: |
          cd ${{ gitea.workspace }} \
          && make apk