name: Windows Release
run-name: Building P3pch4t for Windows
on: 
  push:
    tags:
      - '*'

jobs:
  windows-exe-release:
    runs-on: windows-msys2-build-full
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Flutter pub get
        run: |
          cd ${{ gitea.workspace }}
          flutter pub get
      - name: make version
        run: |
          cd ${{ gitea.workspace }}
          make version_windows
      - name: Build apk
        continue-on-error: false
        run: |
          cd ${{ gitea.workspace }}
          make exe
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          body: |
            This is a **preview** release to be used by testers.
            It was build from **${{ gitea.ref }}** commit `${{ gitea.sha }}`

            ### SECURITY NOTICE

            This build is signed using private key that is commited into the repository. You may prefer to download latest stable release from our download site
            - [static.mrcyjanek.net](https://static.mrcyjanek.net/p3pch4t/latest/)
            - [i2p mirror](http://n6hg3o7vh25bftxxqnspfp7li2rh4wkhbqsd65e5sow7hr4gulrq.b32.i2p/p3pch4t/latest/)

            ### Release info
            ${{ github.event.head_commit.message }}
          files: |-
            ${{ gitea.workspace }}/build/windows/x64/runner/p3pch4t-win64.zip